spring:
  config:
    import: optional:file:.env.development[.properties]
  datasource:
    username: ${dbUserName}
    password: ${dbPassword}
    url: jdbc:mysql://localhost:3306/${dbName}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
    validate-on-migrate: true
    baseline-on-migrate: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: Google
            client-id: ${oauthClientId}
            client-secret: ${oauthClientSecretKey}
            scope:
              - email
custom:
  baseUrl: http://localhost:3000/
  jwt:
    payloads:
      issuer: wjdtn747@naver.com
      subjectAccessToken: access-token
      subjectRefreshToken: refresh-token
      audiance: service-user
    secrets:
      secretKey: ${jwtSecretKey}
      vanillaKey: ${vanillaKey}
    validations:
      access: 900000
      refresh: 1209600000



